## CV2
WIDTH = 960
HEIGHT = 540

SCREEN_SEPARATOR = int(WIDTH/2)
LEFT_WIDTH = SCREEN_SEPARATOR
RIGHT_WIDTH = WIDTH - SCREEN_SEPARATOR


RED = (0, 0, 255)
GREEN = (0, 255, 0)
BLUE = (255, 0, 0)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

CARACTER_HEIGHT = 30
CARACTER_WIDTH = 20

# Coord of all MAIN SCREEN
TOP_LEFT_CORNER = ((0, 0), (int(WIDTH/3), int(HEIGHT/3)))
TOP_RIGHT_CORNER = ((int(2*WIDTH/3), 0), (WIDTH, int(HEIGHT/3)))
BOT_LEFT_CORNER = ((0, int(2*HEIGHT/3)), (int(WIDTH/3), HEIGHT))
BOT_RIGHT_CORNER = ((int(2*WIDTH/3), int(2*HEIGHT/3)), (WIDTH, HEIGHT))
CENTER = ((int(WIDTH/3), int(HEIGHT/3)), (int(2*WIDTH/3), int(2*HEIGHT/3)))

## DETECTION
# ATTENTION LES DONNEES DROITE/GAUCHE SONT INVERSE
SHOW_BONES = True
NOSE = 0
RIGHT_INDEX = 19
LEFT_INDEX = 20
RIGHT_HIP = 23
LEFT_HIP = 24
RIGHT_KNEE = 25
LEFT_KNEE = 26
RIGHT_ANKLE = 27
LEFT_ANKLE = 28

## CONFIG
JUMP_RANGE = 50
SQUAT_RANGE = 90